# This is a basic workflow to help you get started with Actions

name: Paligo Convert to Markdown

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.0.0
        with: 
          python-version: "3.7"
      - name: Install Pandoc and run script
        run: |
          sudo apt-get install pandoc
          pip install pandoc==2.2
          cd scripts
          python unzip-and-transform.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Commit Paligo files via GitHub Actions
